basedir: /

# html lang
language: "it"

# main menu navigation
menu:
  welcome: welcome
  talks_speakers: talk e speaker
  # scommentare per generare pagina
  schedule: schedule
  # menu item for workshop
  workshop: workshop
  sponsor: sponsor

# workshops submenu (comment out if only one workshop: add items for multiple workshops)
workshop_submenu:
   design-system: Design System fantastici e come farli
   ethical-compass: "Ethical Compass: progettare un’innovazione responsabile e consapevole"


# welcome submenu
welcome_submenu:
  about: about
  coc: codice di condotta
  scholarships: scholarships
  where: dove e come
  # delete this row to take out of the menu
  # cfp: call for paper

# stylesheets loaded in the <head>
stylesheets:
- /assets/css/global.css

# scripts loaded in the end of the body / commented out to prevent errors in compiling layout.pug
scripts:
- /assets/js/menu.js
